site_name: Welcome to my professional  website as a KDB/Q developer

site_author: Alexander Unterrainer
site_description: >-
  DESCRIPTION

nav:
  - Home: index.md
  - KDB/Q-Architecture:
    - Plain Vanilla KDB-tick Architecture: architecture/plain.md
    - Ticker Plant in detail: underConstruction.md
  - KDB/Q-Development: underConstruction.md
  - Other: underConstruction.md
  - About: about.md
  - CV: cv.md
  - Services: underConstruction.md

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.sections
#    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: blue grey
      scheme: light
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AUnterrainer
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/alexanderunterrainer/
#    - icon: fontawesome/brands/instagram
#      link: https://www.instagram.com/alexanderunterrainer/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
#  - pymdownx.tabbed:
#      alternate_style: true
#  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
      title: On this page


plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/AUnterrainer"  target="_blank" rel="noopener">Alexander Unterrainer</a>

