site_name: Welcome to my personal website
nav:

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
